dist: bionic

language: c

matrix:
  include:
    - os: linux
      after_success:
        - bash .ci/deploy-docs.sh

    - os: linux
      compiler: clang

    - os: osx
      install:
        - export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # for the docs

before_script:
  - ./autogen.sh
  - ./configure --enable-gtk-doc

script:
  - make check || (cat `find . -name 'test-suite.log'` && false)
  - make distcheck

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - gtk-doc-tools
  homebrew:
    update: true
    packages:
      - freetype
      - fribidi
      - gtk-doc
      - harfbuzz
      - python
