sudo: required # needed for trusty beta
dist: trusty   # needed for HarfBuzz
services:
- docker

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker build -t raqm -f .dockerfile .;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew uninstall libtool && brew install libtool;
      brew install freetype harfbuzz fribidi glib gtk-doc;
      export XML_CATALOG_FILES="/usr/local/etc/xml/catalog";
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" -a "${CC}" == "gcc" ]; then export CC=gcc-4.8; fi

script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      docker run -v `pwd`:/build raqm;
      sh -c "
      cmake -DUNIT_TEST=1 -DWANT_DEBUG=1 -DENABLE_GTK_DOC=1 &&
      make  &&
      make test &&
      make docs
    ";
    fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      which gtkdoc-scan
      cmake -DUNIT_TEST=1 -DWANT_DEBUG=1 -DENABLE_GTK_DOC=1;
      make;
      make test;
      make docs;
   fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CC" == "gcc" -a "$TRAVIS_SECURE_ENV_VARS" == "true" ];
      then bash .ci/deploy-docs.sh;
    fi

notifications:
  email:
    recipients:
      - host-oman@googlegroups.com
